version = "2"
name = "chat-app"

build = "maven build"

run = "java -jar target/chat-app-0.0.1-SNAPSHOT.jar"

# Add environment variables (if needed)
env = {
MONGODB_URI = "mongodb+srv://<username>:<password>@cluster0.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
}
